site_name: Mana's random notes
nav:
    - Home: index.md
    - Random notes:
        - python.md
        - jupyter_notebook.md
        - snakemake.md
        - conda.md
        - containers.md
        - terminal.md
        - bash.md
        - slurm.md
        - bioinformatics.md
        - random.md

theme:
  name: readthedocs
  highlightjs: true

markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition

# site_name: Test the docs
# theme:
#   name: readthedocs
#   highlightjs: true
# plugins:
#   - search
#   - mkdocstrings:
#       handlers:
#         # See: https://mkdocstrings.github.io/python/usage/
#         python:
#           options:
#             docstring_style: sphinx
# markdown_extensions:
#   - markdown_include.include:
#       base_path: .
#   - admonition


